import React from 'react';


const DueTab = () => {
  return (
    <div>
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quia, totam adipisci, delectus odio ab quibusdam ipsam voluptatibus minima velit numquam molestiae in dolorem illum, alias facere vel modi iure molestias hic laboriosam unde quos. Expedita pariatur, quae placeat adipisci iure officia repudiandae praesentium mollitia? Ad quos perspiciatis ex tenetur sit et illo enim voluptate veniam blanditiis aut saepe sed optio sequi ipsum iste, facilis officiis molestias, excepturi earum quam autem libero. Illo, labore exercitationem nam molestiae asperiores culpa a neque ut corrupti iure blanditiis molestias quidem optio eius, maxime minus, quas vitae earum fuga voluptate laborum numquam? Dolor ipsum, fugit repellat officia odio voluptas expedita dignissimos veniam similique neque itaque cumque? Laboriosam aut molestiae maxime ullam officiis illo sit tenetur placeat tempora esse totam, facilis dolore. Amet aliquid accusantium tempora quibusdam dolor aspernatur, magni odio assumenda expedita. Omnis, cum unde nobis necessitatibus dolor dolorem perferendis, voluptatem obcaecati aliquam esse minima facere vel facilis corporis. Id commodi vitae molestiae illo sunt sint quod possimus consequuntur quidem blanditiis. Veritatis animi quia unde illum odit quo corrupti saepe non laboriosam. Ducimus soluta ipsa ad quas aspernatur quam deserunt iure dolore ratione aut. Vel dolor nulla velit ipsam corrupti neque animi maxime, quaerat nihil beatae, doloremque, a eum! Eligendi illum repellat iste deserunt cum esse impedit sit ad rem id, ab voluptatum vitae consequatur dignissimos eveniet omnis magni quas possimus libero dolorum at facere. Adipisci animi eaque veniam voluptas, laborum nemo nulla omnis magni commodi alias nihil reprehenderit a quod ut? Minima optio itaque odit. Molestias libero deserunt quo optio in vero laudantium reiciendis maiores nemo eveniet explicabo debitis cumque ex quibusdam odit ea, repudiandae sit suscipit quas quidem veniam sint magnam officia fugiat. Nesciunt temporibus atque voluptatem cupiditate aut facere ratione corporis eligendi commodi tenetur, tempora id esse quis! Nesciunt asperiores laudantium illo sint minima. Praesentium saepe adipisci mollitia optio dignissimos voluptates nam enim, debitis nisi est maiores accusantium possimus deleniti suscipit nihil a quia sunt hic, repudiandae beatae, amet id. Aperiam, asperiores! Ab perferendis tempora impedit, tempore numquam nihil harum hic eveniet esse facere ducimus quam consequuntur! Accusamus praesentium similique assumenda, beatae earum culpa atque ex magni quisquam expedita facilis iste adipisci eos dicta, quibusdam saepe dignissimos illum, dolore quo ipsam eaque aliquam. Unde cumque, est consequuntur laudantium odio, veniam nisi porro, doloribus illum numquam temporibus pariatur consequatur velit reiciendis. Eius libero cupiditate repellendus maiores pariatur. Ut corrupti dicta cupiditate omnis enim.
    </div>
  );
};

export default DueTab;